language: objective-c

osx_image: xcode8.2

before_install:
   - rvm install 2.2.2
   - sudo gem install bundler
   - sudo gem install cocoapods -v '1.1.1'
   - pod repo update

script:
   travis_retry xcodebuild -workspace AnalyticalAppetite-Example.xcworkspace -scheme AnalyticalAppetite-Example test -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE"
